// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 value = 2;</code>
   * @return The value.
   */
  int getValue();

  /**
   * <code>bool alive = 3;</code>
   * @return The alive.
   */
  boolean getAlive();

  /**
   * <code>.helloworld.RequestedFeature requested_feature = 4;</code>
   * @return The enum numeric value on the wire for requestedFeature.
   */
  int getRequestedFeatureValue();
  /**
   * <code>.helloworld.RequestedFeature requested_feature = 4;</code>
   * @return The requestedFeature.
   */
  io.grpc.examples.helloworld.RequestedFeature getRequestedFeature();
}
